# Generated by Django 4.0.3 on 2022-09-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
