# Generated by Django 4.0.3 on 2022-09-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='other_commnet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
